//! The cross-language parity test.
//!
//! `tests/golden/ladder_scenario.json` was generated by the reference implementation
//! (Python, commit `b11f8df`) and is committed as a **language-neutral contract**. This
//! test replays the same ten-step market scenario through the Rust core and asserts the
//! same decisions come out.
//!
//! That is what makes the port provable rather than hopeful: the unit tests say each
//! rule is right, and this says the whole thing behaves exactly as the implementation it
//! replaced. A refactor that quietly changes sizing, ordering or a boundary fails here
//! even when every unit test still passes.
//!
//! Floats are compared to 1e-9 rather than bit-for-bit, because two languages evaluating
//! the same arithmetic may differ in the last bit. Any real behavioural change is orders
//! of magnitude larger than that.

use std::collections::BTreeMap;
use std::path::PathBuf;

use rungbot_core::{analyze, Bands, Coin, Config, Price, Settings, State, Trail, Venue};
use serde_json::{json, Value};

const T0: f64 = 1_700_000_000.0;
const HOUR: f64 = 3600.0;

fn scenario_config() -> Config {
    // A winner, a loser, a coin on wide bands, and one with no cost basis.
    let coins = vec![
        Coin {
            symbol: "AAA".into(),
            venue: Venue::Binance,
            pair: "AAAUSDT".into(),
            name: "Alpha".into(),
            entry: Some(100.0),
            bands: None,
        },
        Coin {
            symbol: "BBB".into(),
            venue: Venue::Gate,
            pair: "BBB_USDT".into(),
            name: "Beta".into(),
            entry: Some(2.0),
            bands: None,
        },
        Coin {
            symbol: "CCC".into(),
            venue: Venue::Binance,
            pair: "CCCUSDT".into(),
            name: "Gamma".into(),
            entry: Some(0.5),
            bands: Some(Bands {
                first_pct: 15.0,
                step_pct: 8.0,
            }),
        },
        Coin {
            symbol: "DDD".into(),
            venue: Venue::Coingecko,
            pair: "delta".into(),
            name: "Delta".into(),
            entry: None,
            bands: None,
        },
    ];
    let settings = Settings {
        bands: Bands {
            first_pct: 10.0,
            step_pct: 5.0,
        },
        min_trade_pct: 1.0,
        min_core_pct: 20.0,
        window_hours: 24.0,
        buy_floor_pct: 50.0,
        target_pct: 10.0,
        breaker_pct: 40.0,
        breaker_days: 7.0,
        trail: Trail::Off,
        trail_giveback_pct: 5.0,
    };
    Config::new(coins, settings).expect("scenario config is valid")
}

/// One coin's quote in a scenario step: symbol, price, 24h change.
type Quote = (&'static str, f64, f64);
/// One market step: hours since `T0`, and a quote for each of the four coins.
type Step = (f64, [Quote; 4]);

/// A month of market in ten steps.
#[rustfmt::skip]
const SCENARIO: &[Step] = &[
    (0.0,        [("AAA", 100.0, 0.5),  ("BBB", 2.00, -1.0),  ("CCC", 0.50, 2.0),   ("DDD", 10.0, 0.0)]),
    (1.0,        [("AAA", 88.0, -12.0), ("BBB", 1.90, -5.0),  ("CCC", 0.46, -8.0),  ("DDD", 8.5, -15.0)]),
    (2.0,        [("AAA", 84.0, -16.0), ("BBB", 1.80, -10.0), ("CCC", 0.41, -18.0), ("DDD", 8.0, -20.0)]),
    (26.0,       [("AAA", 95.0, 5.0),   ("BBB", 1.85, 2.0),   ("CCC", 0.44, 3.0),   ("DDD", 9.0, 6.0)]),
    (50.0,       [("AAA", 115.0, 8.0),  ("BBB", 1.50, -12.0), ("CCC", 0.60, 20.0),  ("DDD", 12.0, 15.0)]),
    (74.0,       [("AAA", 135.0, 6.0),  ("BBB", 1.10, -18.0), ("CCC", 0.75, 12.0),  ("DDD", 11.0, -8.0)]),
    (98.0,       [("AAA", 160.0, 4.0),  ("BBB", 0.95, -9.0),  ("CCC", 0.90, 10.0),  ("DDD", 14.0, 12.0)]),
    (24.0 * 9.0, [("AAA", 150.0, -2.0), ("BBB", 0.92, -1.0),  ("CCC", 0.85, -3.0),  ("DDD", 13.0, -4.0)]),
    (24.0 * 12.0,[("AAA", 145.0, -1.0), ("BBB", 0.80, -14.0), ("CCC", 0.80, -2.0),  ("DDD", 9.0, -30.0)]),
    (24.0 * 30.0,[("AAA", 250.0, 9.0),  ("BBB", 0.75, -3.0),  ("CCC", 1.40, 25.0),  ("DDD", 6.0, -55.0)]),
];

fn state_to_json(state: &State) -> Value {
    let mut out = serde_json::Map::new();
    for (sym, st) in state {
        out.insert(
            sym.clone(),
            json!({
                "buy": st.buy,
                "sell": st.sell,
                "deployed_pct": st.deployed_pct,
                "sold_pct": st.sold_pct,
                "win_until": st.win_until,
                "win_dir": st.win_dir,
                "cost_basis": st.cost_basis,
                "below_since": st.below_since,
                "breaker": st.breaker,
                "peak_pnl": st.peak_pnl,
            }),
        );
    }
    Value::Object(out)
}

fn run_scenario() -> Value {
    let cfg = scenario_config();
    let mut state: State = BTreeMap::new();
    let mut steps: Vec<Value> = Vec::new();

    for (hours, quotes) in SCENARIO {
        let now = T0 + hours * HOUR;
        let mut prices: BTreeMap<String, Price> = BTreeMap::new();
        for (sym, price, chg) in quotes {
            prices.insert(
                sym.to_string(),
                Price {
                    price: *price,
                    chg_24h: Some(*chg),
                },
            );
        }
        let out = analyze(&cfg, &prices, &state, now);
        state = out.state;

        steps.push(json!({
            // The fixture stores whole hours as integers, matching the reference run.
            "hours": *hours as i64,
            "buys": out.buys.iter().map(|b| json!({
                "sym": b.row.sym, "rung": b.rung, "buy_pct": b.pct, "capped": b.capped,
            })).collect::<Vec<_>>(),
            "sells": out.sells.iter().map(|s| json!({
                "sym": s.row.sym, "rung": s.rung, "sell_pct": s.pct, "capped": s.capped,
            })).collect::<Vec<_>>(),
            "errors": out.errors,
            "state": state_to_json(&state),
        }));
    }
    json!({ "scenario": steps })
}

/// Structural comparison that tolerates last-bit float differences but nothing else.
fn diff(path: &str, got: &Value, want: &Value, out: &mut Vec<String>) {
    match (got, want) {
        (Value::Number(a), Value::Number(b)) => {
            let (x, y) = (
                a.as_f64().unwrap_or(f64::NAN),
                b.as_f64().unwrap_or(f64::NAN),
            );
            if (x - y).abs() > 1e-9 {
                out.push(format!("{path}: got {x}, want {y}"));
            }
        }
        (Value::Object(a), Value::Object(b)) => {
            let mut keys: Vec<&String> = a.keys().chain(b.keys()).collect();
            keys.sort();
            keys.dedup();
            for k in keys {
                match (a.get(k), b.get(k)) {
                    (Some(x), Some(y)) => diff(&format!("{path}.{k}"), x, y, out),
                    (None, Some(y)) => out.push(format!("{path}.{k}: missing, want {y}")),
                    (Some(x), None) => out.push(format!("{path}.{k}: unexpected {x}")),
                    (None, None) => unreachable!(),
                }
            }
        }
        (Value::Array(a), Value::Array(b)) => {
            if a.len() != b.len() {
                out.push(format!("{path}: got {} items, want {}", a.len(), b.len()));
                return;
            }
            for (i, (x, y)) in a.iter().zip(b).enumerate() {
                diff(&format!("{path}[{i}]"), x, y, out);
            }
        }
        (a, b) if a != b => out.push(format!("{path}: got {a}, want {b}")),
        _ => {}
    }
}

#[test]
fn matches_the_reference_implementation() {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/ladder_scenario.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read the golden fixture at {}: {e}", path.display()));
    let want: Value = serde_json::from_str(&raw).expect("the golden fixture is valid JSON");

    let mut failures = Vec::new();
    diff("", &run_scenario(), &want, &mut failures);

    assert!(
        failures.is_empty(),
        "the Rust core diverged from the reference implementation in {} place(s):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}
